apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: tendermintnodeone # give any name
spec:
 replicas: 1
 template:
   metadata:
     name: tendermintnodeone
     labels:
       run: tendermint1
   spec:
     containers:
       - name: node1
         image: "blockchain-validator1:latest" # your registery name
         imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
 name: my-service-tendermint-1 # give a service name
 labels:
   run: tendermint1
spec:
 type: NodePort
 selector:
   run: tendermint1
 ports:
  - protocol: TCP
    name: tendermintrpcport
    port: 30090 
    nodePort: 30090 
  - protocol: TCP
    name: tendermintpeerport
    port: 30091 
    nodePort: 30091  