apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: tendermintnodetwo # give any name
spec:
 replicas: 1
 template:
   metadata:
     name: tendermintnodetwo
     labels:
       run: tendermint2
   spec:
     containers:
       - name: node2
         image: "blockchain-validator2:latest" # your registery name
         imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
 name: my-service-tendermint-2 # give a service name
 labels:
   run: tendermint2
spec:
 type: NodePort
 selector:
   run: tendermint2
 ports:
  - protocol: TCP
    name: tendermintrpcport
    port: 30092 
    nodePort: 30092
  - protocol: TCP
    name: tendermintpeerport
    port: 30093 
    nodePort: 30093 