apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: tendermintnodetwo # give any name
spec:
 replicas: 1
 template:
   metadata:
     name: tendermintnodetwo
     labels:
       run: tendermint3
   spec:
     containers:
       - name: saif1cluster
         image: "registry.eu-de.bluemix.net/tendermint3/node2" # your registery name
         imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
 name: my-service-tendermint-11 # give a service name
 labels:
   run: tendermint3
spec:
 type: NodePort
 selector:
   run: tendermint3
 ports:
  - protocol: TCP
    name: tendermint
    port: 30090  # it shall be 8545 and no other port !!!!!
    nodePort: 30090  # Give a port to access the application publically
  - protocol: TCP
    name: port
    port: 30092  # it shall be 8545 and no other port !!!!!
    nodePort: 30092  # Give a port to access the application publically