apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: userservice # give any name
spec:
 replicas: 1
 template:
   metadata:
     name: userservice
     labels:
       run: tendermint3
   spec:
     containers:
       - name: servicecluster
         image: "registry.eu-de.bluemix.net/tendermint3/node2" # your registery name
         imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
 name: my-service-tendermint-11 # give a service name
 labels:
   run: tendermint3
spec:
 type: NodePort
 selector:
   run: tendermint3
 ports:
  - protocol: TCP
    name: tendermint
    port: 1234  # it shall be 8545 and no other port !!!!!
    nodePort: 30090  # Give a port to access the application publically