apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: user-service 
spec:
 replicas: 1
 template:
   metadata:
     name: user-service
     labels:
       run: userservice
   spec:
     containers:
       - name: user-service-container
         image: "user-service" 
         imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
 name: userservice 
 labels:
   run: userservice
spec:
 type: NodePort
 selector:
   run: userservice
 ports:
  - protocol: TCP
    name: userservice
    port: 30095  
    nodePort: 30095