apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: user-service # give any name
spec:
 replicas: 1
 template:
   metadata:
     name: user-service
     labels:
       run: userservice
   spec:
     containers:
       - name: userServiceContainer
         image: "user-service-image" # your registery name
         imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
 name: userservice # give a service name
 labels:
   run: userservice
spec:
 type: NodePort
 selector:
   run: userservice
 ports:
  - protocol: TCP
    name: userservice
    port: 1234  
    nodePort: 30090